version: '3'
services:
    cups:
        image: 'olbat/cupsd:2023-02-10'
        container_name: cups
        ports:
            - '631:631'
        volumes:
            - 'print-processor-dbus:/var/run/dbus'
            - 'print-processor-cups:/etc/cups'
        restart: unless-stopped
        networks:
            - print-processor

    supervisor:
        image: ghcr.io/kjsoftware/print-processor-supervisor
        container_name: supervisor
        env_file:
          - .env
        ports:
            - '80:22'
        networks:
            - print-processor

networks:
    print-processor:

volumes:
    print-processor-dbus:
    print-processor-cups: